In [93]:
# Date: 2026-02-04
# Author: Haji Suleman
# Project: 🩺 Chronic Kidney Disease (CKD) Prediction System


import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [94]:
df = pd.read_csv("./kidney_disease.csv")

df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [95]:
df["classification"] = df["classification"].str.strip()
df["classification"].value_counts()

classification
ckd       250
notckd    150
Name: count, dtype: int64

In [96]:
df.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [97]:
df.shape

(400, 26)

In [98]:
df = df.dropna()
df.shape

(158, 26)

In [99]:
df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,...,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,...,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
14,14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,...,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
20,20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,...,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd

In [100]:
df["rbc"].value_counts()

rbc
normal      140
abnormal     18
Name: count, dtype: int64

In [101]:
df["rbc"] = df["rbc"].map({"normal": 1, "abnormal": 0})
df["rbc"].value_counts()

rbc
1    140
0     18
Name: count, dtype: int64

In [102]:
df["pc"].value_counts()

pc
normal      129
abnormal     29
Name: count, dtype: int64

In [103]:
df["pc"] = df["pc"].map({"normal":1,"abnormal":0})
df["pc"].value_counts()

pc
1    129
0     29
Name: count, dtype: int64

In [104]:
df["pcc"].value_counts()

pcc
notpresent    144
present        14
Name: count, dtype: int64

In [105]:
df["pcc"] = df["pcc"].map({"present": 1, "notpresent": 0})
df["pcc"].value_counts()

pcc
0    144
1     14
Name: count, dtype: int64

In [106]:
df["ba"].value_counts()

ba
notpresent    146
present        12
Name: count, dtype: int64

In [ ]:
df["ba"] = df["ba"].map({"present":1,"notpresent":0})
df["ba"].value_counts()

ba
0    146
1     12
Name: count, dtype: int64